#!/bin/bash

set -e

mouse_id=$(xinput list | grep 'Logitech USB-PS/2 Optical Mouse' | sed -r 's/^.*[\t ]id=([0-9]+)[\t ].*$/\1/')
natural_scrolling_id=$(xinput list-props $mouse_id | egrep 'Natural Scrolling Enabled \([0-9]+\):' | sed -r 's/.*\(([0-9]+)\):.*/\1/')

xinput set-prop $mouse_id $natural_scrolling_id 1

