#!/bin/bash

set -e

backup() {
    local dotfile="$1"
    if [ -f "$HOME/.$dotfile" ]; then
        mv "$HOME/.$dotfile" "$HOME/dot.$dotfile.bak"
        echo "Backed up $HOME/.$dotfile as $HOME/dot.$dotfile.bak"
    fi
}

backup "bash_profile"
backup "profile"
backup "bash_login"
backup "bashrc"

ln -nfs $(pwd)/dot.bash_functions.sh "$HOME/.bash_functions"
ln -nfs $(pwd)/dot.bash_login.sh "$HOME/.bash_login"
ln -nfs $(pwd)/dot.bashrc.sh "$HOME/.bashrc"
ln -nfs $(pwd)/dot.colordiffrc "$HOME/.colordiffrc"
ln -nfs $(pwd)/dot.gemrc "$HOME/.gemrc"
ln -nfs $(pwd)/dot.gitconfig "$HOME/.gitconfig"
ln -nfs $(pwd)/dot.vimrc "$HOME/.vimrc"

mkdir -p ~/.local/bin
ln -nfs $(pwd)/lessfilter-highlight.sh ~/.local/bin/lessfilter-highlight

if [ "$(uname)" = 'Darwin' ]; then
    sed "s#\${HOME}#$HOME#g" < $(pwd)/environment.plist.in > ~/Library/LaunchAgents/environment.plist
    ln -nfs $(pwd)/ssh-keychain.plist ~/Library/LaunchAgents/
    ln -nfs $(pwd)/library-path.plist ~/Library/LaunchAgents/
    read -p 'Enter API token for Homebrew: ' HOMEBREW_GITHUB_API_TOKEN
    sed "s#\${HOMEBREW_GITHUB_API_TOKEN}#$HOMEBREW_GITHUB_API_TOKEN#g" < $(pwd)/homebrew.plist.in > ~/Library/LaunchAgents/homebrew.plist
    [ ! -d ~/.gnupg ] && install -d -m 0700 ~/.gnupg
    echo 'pinentry-program /usr/local/bin/pinentry-mac' >> ~/.gnupg/gpg-agent.conf
fi

mkdir -p ~/.vim/autoload ~/.vim/bundle
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

git clone https://github.com/tpope/vim-sensible.git        ~/.vim/bundle/vim-sensible
git clone https://github.com/itchyny/lightline.vim.git     ~/.vim/bundle/lightline.vim
git clone https://github.com/tpope/vim-fugitive.git        ~/.vim/bundle/vim-fugitive
git clone https://github.com/airblade/vim-gitgutter.git    ~/.vim/bundle/vim-gitgutter
git clone https://github.com/w0rp/ale.git                  ~/.vim/bundle/ale
git clone https://github.com/junegunn/fzf.vim.git          ~/.vim/bundle/fzf.vim
git clone https://github.com/robbles/logstash.vim.git      ~/.vim/bundle/logstash.vim
git clone https://github.com/derekwyatt/vim-scala.git      ~/.vim/bundle/vim-scala
git clone https://github.com/rust-lang/rust.vim.git        ~/.vim/bundle/rust.vim
git clone https://github.com/neovimhaskell/haskell-vim.git ~/.vim/bundle/haskell-vim

