#!/bin/bash


collect_existing_files() {
    local result
    for f in "$@"; do
	[ -f $HOME/$f ] && result="$result $HOME/$f"
    done
    echo $result
}


echo "About to overwrite following files in ${HOME}:"
for src_dotfile in dot.*.sh; do
    target_dotfile=$(echo $src_dotfile | sed 's/^dot\.\(.*\)\.sh$/.\1/')
    [ -f "$HOME/$target_dotfile" ] && echo -e '\t' $target_dotfile
done

read -ep "Continue? " please_continue
if [ "$please_continue" != "y" ]; then
    echo "Aborted"
    exit 1
fi

for src_dotfile in dot.*.sh; do
    target_dotfile=$(echo $src_dotfile | sed 's/^dot\.\(.*\)\.sh$/.\1/')
    echo "${src_dotfile} -> ${target_dotfile}"
    cp "$src_dotfile" "$HOME/$target_dotfile"
done

maybe_remove=$(collect_existing_files .profile .bash_profile .emacs .emacs.el)
if [ "$maybe_remove" != "" ]; then
    echo "You may want to remove or rename the following files:"
    for f in $maybe_remove; do
	echo -e "\t$f"
    done
fi
