#!/bin/bash

git ls-files \
    | rsync \
        --recursive \
        --relative \
        --update \
        --inplace \
        --dirs \
        --links \
        --safe-links \
        --perms \
        --executability \
        --times \
        --compress \
        --files-from=- \
        --itemize-changes \
        . \
        "$1":.dotfiles/

ssh "$1" <<EOF
  mkdir -p .vim
  ln -nsf .dotfiles/dot.ackrc .ackrc
  ln -nsf .dotfiles/dot.bash_login.sh .bash_login
  ln -nsf .dotfiles/dot.bashrc.sh .bashrc
  ln -nsf .dotfiles/dot.colordiffrc .colordiffrc
  ln -nsf .dotfiles/dot.environment.sh .environment
  ln -nsf .dotfiles/dot.funcs.decl.sh .funcs.decl
  ln -nsf .dotfiles/dot.funcs.clean.sh .funcs.clean
  ln -nsf .dotfiles/dot.gemrc .gemrc
  ln -nsf .dotfiles/dot.gitattributes .gitattributes
  ln -nsf .dotfiles/dot.gitconfig .gitconfig
  ln -nsf .dotfiles/dot.gnomerc.sh .gnomerc
  ln -nsf .dotfiles/dot.lessfilter .lessfilter
  ln -nsf .dotfiles/dot.npmrc .npmrc
  ln -nsf .dotfiles/dot.vimrc .vimrc
  [ -f .bash_profile ] && mv .bash_profile backup.dot.bash_profile
  [ -f .profile ] && mv .profile backup.dot.profile
EOF

if [ -d "$HOME/.vim/bundle" ]; then
    rsync --archive --compress "$HOME/.vim/bundle" "$1":.vim/
fi

