(custom-set-variables
  ;; custom-set-variables was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(bookmark-default-file "~/.emacs.d/bookmark")
 '(bookmark-save-flag 1)
 '(blink-cursor-mode nil)
 '(c-default-style "linux")
 '(c-echo-syntactic-information-p t)
 '(c-report-syntactic-errors t)
 '(case-fold-search t)
 '(column-number-mode t)
 '(comment-style (quote aligned))
 '(compilation-auto-jump-to-first-error t)
 '(compilation-scroll-output t)
 '(compilation-window-height 7)
 '(compile-command "make")
 '(custom-file "~/.emacs.d/customizations.el")
 '(custom-theme-directory "~/.emacs.d/themes/")
 '(default-indicate-empty-lines t t)
 '(delete-selection-mode t)
 '(gdb-enable-debug nil)
 '(gdb-many-windows t)
 '(gdb-memory-unit "b")
 '(gdb-show-main t)
 '(gdb-speedbar-auto-raise t)
 '(gdb-use-separate-io-buffer t)
 '(global-font-lock-mode t nil (font-lock))
 '(global-hl-line-mode t)
 '(global-linum-mode t)
 '(ido-case-fold nil)
 '(ido-everywhere t)
 '(ido-mode (quote both) nil (ido))
 '(ido-save-directory-list-file "~/.emacs.d/ido.last")
 '(inhibit-startup-screen t)
 '(initial-scratch-message nil)
 '(isearch-resume-in-command-history t)
 '(iswitchb-buffer-ignore (quote ("^ " "^\\*")))
 '(iswitchb-mode t)
 '(next-line-add-newlines nil)
 '(recentf-mode t)
 '(recentf-save-file "~/.emacs.d/recentf")
 '(save-place t nil (saveplace))
 '(save-place-file "~/.emacs.d/places")
 '(scroll-bar-mode (quote right))
 '(scroll-conservatively 100)
 '(scroll-preserve-screen-position 1)
 '(show-paren-mode t)
 '(size-indication-mode t)
 '(speedbar-default-position (quote right))
 '(sr-speedbar-skip-other-window-p t)
 '(tags-revert-without-query t)
 '(tool-bar-mode nil)
 '(track-eol nil)
 '(transient-mark-mode t)
 '(url-handler-mode t)
 '(view-read-only t)
 '(visible-bell t)
 '(which-function-mode t)
 '(whitespace-line-column -1)
 '(x-stretch-cursor t))
(custom-set-faces
  ;; custom-set-faces was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
)
